GET http://localhost:8000/links
Authorization: Bearer eyJpc3N1ZXIiOiJTaHJpbmtJdCIsImFsZyI6ImRpciIsImVuYyI6IkExMjhDQkMtSFMyNTYifQ..i180r2SfL-iJADAiWQZBQA.zwDmGobPEfpQZmPftaZK0opm1Drz_sM4SLKL5gm6qHJrgNkKchWZTxnhgobm05n7BJOkjN1HByxEpgxuT5UKkK9YpisHvSFj__8UY236nIYZ4bUM8V8V9JEhcXMvxxkrGya_phAQiSbmlWJxJXBoF0V28VookgyBKmCS0fqLwGxQM6siB_Q0rbs5dfLKM9FDYFonDpJNJXZ9ZrpdGxlEBYM9ITyYN3WHGqpbfn4EzNX6bLvPORZuw5KU2exm39RC.xV0B6f7sPWYKor9CEeaJ9g
