GET http://localhost:8000/links/shortcut/33e5T7sH
Authorization: Bearer eyJpc3N1ZXIiOiJTaHJpbmtJdCIsImFsZyI6ImRpciIsImVuYyI6IkExMjhDQkMtSFMyNTYifQ..znlpolHIJTFkJeOYYj9iMw.Y_kxlHxCkPpYAcY2CaysdKg3rTYebNM5PZoTQBDozcBn8AYZof4JV_odJheS6TYMwkfHtIjP7qwYM6RFP5OXbmrrlCX-4XuD9WA3dYxyESLHla-ZQtfwRiNzek_y60mvNjkiYFLNxWjdebGjGhMxSmdZxmLHadcmx6GefvV5Rq29rWh7ir0B1e4iNn1-zIeFhh0QH2bIdX66dauuxVu_t1c2PiSu-Xw-DYiACE_PsMOIfcvdQz0V5QVOBnx32XmR.sLGgnn_doxPaHxDeGlKj-Q
