services:
  db:
    image: postgres:17.5-bookworm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shrinkit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shrinikit
  api:
    build:
      context: server
#      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shrinkit
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - shrinikit

networks:
  shrinikit: { }

volumes:
  postgres_data:
    driver: local
