POST http://localhost:8000/users/register
Content-Type: application/json

{
  "request": {
    "role": "NORMAL_USER",
    "username": "testuser5",
    "password": "testuser5",
    "name": "Test User 5"
  }
}
